### ISSUE TITLE
problem with set token

### ISSUE THREAD

**Issue by vincent1bt** [francois-blanchard/riot_lol_api#1]
i have this "dynamic constant assignment" when i try to put the set token
  RiotLolApi::TOKEN

**Comment by francois-blanchard** [comment]
I need more details for help you.
Send me your code and the stack errors please.

**Comment by vincent1bt** [comment]
THE CONTROLLER
class CustomerController < ApplicationController
  def index
    RiotLolApi::TOKEN = "Mykey"
    client = RiotLolApi::Client.new(:region => 'lan')
    summoner = client.get_summoner_by_name '1kilodetortillas'
  end
end
THE ERROR
/Users/vincent/Progra/rails/lol_app/app/controllers/customer_controller.rb:3: dynamic constant assignment RiotLolApi::TOKEN = "Mykey" ^

thank you if you can help me

**Comment by francois-blanchard** [comment]
RiotLolApi::TOKEN is a constant, so you can't assign it in your controller.
Set `RiotLolApi::TOKEN = "Mykey"` in `config/initializers/riot_api.rb` for example.

**Comment by vincent1bt** [comment]
thanks a lot, now works!

**Comment by francois-blanchard** [comment]
np ;)
