### ISSUE TITLE
Allow retrieval of more than 10 games

### ISSUE THREAD

**Issue by 0xtobit** [francois-blanchard/riot_lol_api#2]
It would be nice if I could get more than 10 recent games for a summoner.

**Comment by francois-blanchard** [comment]
Yes, it would be nice. 
But Riot Game Api doesn't allow to get more than 10 last games.

**Comment by 0xtobit** [comment]
Can the match_history method with indexing be used to expand the functionality?

**Comment by francois-blanchard** [comment]
You can get all ranked matchs with `match list` method
