### ISSUE TITLE
Fail to initialize

### ISSUE THREAD

**Issue by nccmike** [francois-blanchard/riot_lol_api#5]
I am trying to use the gem with Rails 4.2.5.1

When initializing, I keep getting the error:
NoMethodError: undefined method `region' for #<RiotLolApi::Client:0x007fb4e03f2248>
    from /Users/mike/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/riot_lol_api-0.3.2/lib/riot_lol_api/clients.rb:19:in`initialize'

I have tried to initialize in via a file and tried to do it strictly from the rails console, and I get the same error.

I am sure this is a simplistic issue since I am certainly not a coding genius. Any help would be appreciated.

**Comment by francois-blanchard** [comment]
Show me your initialize code pls.
Which gem version do you use ?

**Comment by hankditton** [comment]
I'm getting the same problem, in both console or from a file. Using gem version 0.3.2. Just running the code from the readme produces this error:

```
# Create client
client = RiotLolApi::Client.new do |config|
  config.region = 'your_region'
  config.api_key = 'xxxxxxxxxxxx'
end

# Start get data
summoner = client.get_summoner_by_name 'your_summoner_name'
```

```
/Users/Hank/.rvm/gems/ruby-2.2.5/gems/riot_lol_api-0.3.2/lib/riot_lol_api/clients.rb:19:in `initialize': undefined method `region' for #<RiotLolApi::Client:0x007fd56d0a43e0> (NoMethodError)
    from clientTest.rb:3:in `new'
    from clientTest.rb:3:in `<main>'
```

**Comment by hankditton** [comment]
Looks like this is caused because a new version of the gem was not bumped for changes 29c3126 and 7336c30. The documentation in the readme is correct for the current code in the repo, but that is not what you get when install 0.3.2 from gem.

**Comment by francois-blanchard** [comment]
Yes, I fixed it.

Version 3.3 is available on [Github](https://github.com/francois-blanchard/riot_lol_api/releases/tag/3.3) and [Rubygems](https://rubygems.org/gems/riot_lol_api) 😄
